"""
Immutable constants for the Reverse Engineering SDK.
"""

EDGE_TYPE_EXTRACTED = "EXTRACTED"
EDGE_TYPE_INFERRED = "INFERRED"
EDGE_TYPE_AMBIGUOUS = "AMBIGUOUS"

CONFIDENCE_THRESHOLD_HIGH = 0.9
CONFIDENCE_THRESHOLD_MEDIUM = 0.7

MAX_FILE_LINES_GUARD = 150
DEFAULT_TOKEN_BUDGET = 8000
